(function() {var implementors = {};
implementors["arrayvec"] = [{"text":"impl&lt;A:&nbsp;Array&lt;Item = u8&gt;&gt; Write for ArrayVec&lt;A&gt;","synthetic":false,"types":[]}];
implementors["base64"] = [{"text":"impl&lt;W:&nbsp;Write&gt; Write for EncoderWriter&lt;W&gt;","synthetic":false,"types":[]},{"text":"impl&lt;S:&nbsp;StrConsumer&gt; Write for EncoderStringWriter&lt;S&gt;","synthetic":false,"types":[]}];
implementors["bytes"] = [{"text":"impl&lt;B:&nbsp;BufMut + Sized&gt; Write for Writer&lt;B&gt;","synthetic":false,"types":[]}];
implementors["deflate"] = [{"text":"impl&lt;W:&nbsp;Write&gt; Write for DeflateEncoder&lt;W&gt;","synthetic":false,"types":[]},{"text":"impl&lt;W:&nbsp;Write&gt; Write for ZlibEncoder&lt;W&gt;","synthetic":false,"types":[]}];
implementors["either"] = [{"text":"impl&lt;L, R&gt; Write for Either&lt;L, R&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;L: Write,<br>&nbsp;&nbsp;&nbsp;&nbsp;R: Write,&nbsp;</span>","synthetic":false,"types":[]}];
implementors["env_logger"] = [{"text":"impl Write for Formatter","synthetic":false,"types":[]}];
implementors["png"] = [{"text":"impl&lt;'a, W:&nbsp;Write&gt; Write for StreamWriter&lt;'a, W&gt;","synthetic":false,"types":[]}];
implementors["smithay_client_toolkit"] = [{"text":"impl Write for WritePipe","synthetic":false,"types":[]},{"text":"impl Write for MemPool","synthetic":false,"types":[]}];
implementors["termcolor"] = [{"text":"impl Write for StandardStream","synthetic":false,"types":[]},{"text":"impl&lt;'a&gt; Write for StandardStreamLock&lt;'a&gt;","synthetic":false,"types":[]},{"text":"impl Write for BufferedStandardStream","synthetic":false,"types":[]},{"text":"impl Write for Buffer","synthetic":false,"types":[]},{"text":"impl&lt;W:&nbsp;Write&gt; Write for NoColor&lt;W&gt;","synthetic":false,"types":[]},{"text":"impl&lt;W:&nbsp;Write&gt; Write for Ansi&lt;W&gt;","synthetic":false,"types":[]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()