(function() {var implementors = {};
implementors["andrew"] = [{"text":"impl Octal for Sides","synthetic":false,"types":[]}];
implementors["env_logger"] = [{"text":"impl&lt;'a, T:&nbsp;Octal&gt; Octal for StyledValue&lt;'a, T&gt;","synthetic":false,"types":[]}];
implementors["gfx_hal"] = [{"text":"impl Octal for Usage","synthetic":false,"types":[]},{"text":"impl Octal for Access","synthetic":false,"types":[]},{"text":"impl Octal for CommandBufferFlags","synthetic":false,"types":[]},{"text":"impl Octal for Aspects","synthetic":false,"types":[]},{"text":"impl Octal for ImageFeature","synthetic":false,"types":[]},{"text":"impl Octal for BufferFeature","synthetic":false,"types":[]},{"text":"impl Octal for ViewCapabilities","synthetic":false,"types":[]},{"text":"impl Octal for Usage","synthetic":false,"types":[]},{"text":"impl Octal for Access","synthetic":false,"types":[]},{"text":"impl Octal for Properties","synthetic":false,"types":[]},{"text":"impl Octal for Dependencies","synthetic":false,"types":[]},{"text":"impl Octal for CommandPoolCreateFlags","synthetic":false,"types":[]},{"text":"impl Octal for DescriptorPoolCreateFlags","synthetic":false,"types":[]},{"text":"impl Octal for ColorMask","synthetic":false,"types":[]},{"text":"impl Octal for Face","synthetic":false,"types":[]},{"text":"impl Octal for PipelineStage","synthetic":false,"types":[]},{"text":"impl Octal for ShaderStageFlags","synthetic":false,"types":[]},{"text":"impl Octal for PipelineCreationFlags","synthetic":false,"types":[]},{"text":"impl Octal for ControlFlags","synthetic":false,"types":[]},{"text":"impl Octal for ResultFlags","synthetic":false,"types":[]},{"text":"impl Octal for PipelineStatistic","synthetic":false,"types":[]},{"text":"impl Octal for CompositeAlpha","synthetic":false,"types":[]},{"text":"impl Octal for Features","synthetic":false,"types":[]}];
implementors["itertools"] = [{"text":"impl&lt;'a, I&gt; Octal for Format&lt;'a, I&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;I: Iterator,<br>&nbsp;&nbsp;&nbsp;&nbsp;I::Item: Octal,&nbsp;</span>","synthetic":false,"types":[]}];
implementors["nalgebra"] = [{"text":"impl&lt;N, R:&nbsp;Dim, C:&nbsp;Dim, S&gt; Octal for Matrix&lt;N, R, C, S&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;N: Scalar + Octal,<br>&nbsp;&nbsp;&nbsp;&nbsp;S: Storage&lt;N, R, C&gt;,<br>&nbsp;&nbsp;&nbsp;&nbsp;DefaultAllocator: Allocator&lt;usize, R, C&gt;,&nbsp;</span>","synthetic":false,"types":[]}];
implementors["nix"] = [{"text":"impl Octal for AtFlags","synthetic":false,"types":[]},{"text":"impl Octal for OFlag","synthetic":false,"types":[]},{"text":"impl Octal for SealFlag","synthetic":false,"types":[]},{"text":"impl Octal for FdFlag","synthetic":false,"types":[]},{"text":"impl Octal for SpliceFFlags","synthetic":false,"types":[]},{"text":"impl Octal for FallocateFlags","synthetic":false,"types":[]},{"text":"impl Octal for ModuleInitFlags","synthetic":false,"types":[]},{"text":"impl Octal for DeleteModuleFlags","synthetic":false,"types":[]},{"text":"impl Octal for MsFlags","synthetic":false,"types":[]},{"text":"impl Octal for MntFlags","synthetic":false,"types":[]},{"text":"impl Octal for MQ_OFlag","synthetic":false,"types":[]},{"text":"impl Octal for FdFlag","synthetic":false,"types":[]},{"text":"impl Octal for InterfaceFlags","synthetic":false,"types":[]},{"text":"impl Octal for PollFlags","synthetic":false,"types":[]},{"text":"impl Octal for CloneFlags","synthetic":false,"types":[]},{"text":"impl Octal for EpollFlags","synthetic":false,"types":[]},{"text":"impl Octal for EpollCreateFlags","synthetic":false,"types":[]},{"text":"impl Octal for EfdFlags","synthetic":false,"types":[]},{"text":"impl Octal for MemFdCreateFlag","synthetic":false,"types":[]},{"text":"impl Octal for ProtFlags","synthetic":false,"types":[]},{"text":"impl Octal for MapFlags","synthetic":false,"types":[]},{"text":"impl Octal for MsFlags","synthetic":false,"types":[]},{"text":"impl Octal for MlockAllFlags","synthetic":false,"types":[]},{"text":"impl Octal for Options","synthetic":false,"types":[]},{"text":"impl Octal for QuotaValidFlags","synthetic":false,"types":[]},{"text":"impl Octal for SaFlags","synthetic":false,"types":[]},{"text":"impl Octal for SfdFlags","synthetic":false,"types":[]},{"text":"impl Octal for SockFlag","synthetic":false,"types":[]},{"text":"impl Octal for MsgFlags","synthetic":false,"types":[]},{"text":"impl Octal for SFlag","synthetic":false,"types":[]},{"text":"impl Octal for Mode","synthetic":false,"types":[]},{"text":"impl Octal for FsFlags","synthetic":false,"types":[]},{"text":"impl Octal for InputFlags","synthetic":false,"types":[]},{"text":"impl Octal for OutputFlags","synthetic":false,"types":[]},{"text":"impl Octal for ControlFlags","synthetic":false,"types":[]},{"text":"impl Octal for LocalFlags","synthetic":false,"types":[]},{"text":"impl Octal for WaitPidFlag","synthetic":false,"types":[]},{"text":"impl Octal for AddWatchFlags","synthetic":false,"types":[]},{"text":"impl Octal for InitFlags","synthetic":false,"types":[]},{"text":"impl Octal for AccessFlags","synthetic":false,"types":[]}];
implementors["num_bigint"] = [{"text":"impl Octal for BigInt","synthetic":false,"types":[]},{"text":"impl Octal for BigUint","synthetic":false,"types":[]}];
implementors["num_complex"] = [{"text":"impl&lt;T&gt; Octal for Complex&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: Octal + Num + PartialOrd + Clone,&nbsp;</span>","synthetic":false,"types":[]}];
implementors["num_rational"] = [{"text":"impl&lt;T:&nbsp;Octal + Clone + Integer&gt; Octal for Ratio&lt;T&gt;","synthetic":false,"types":[]}];
implementors["png"] = [{"text":"impl Octal for Transformations","synthetic":false,"types":[]}];
implementors["ron"] = [{"text":"impl Octal for Extensions","synthetic":false,"types":[]}];
implementors["tinyvec"] = [{"text":"impl&lt;A:&nbsp;Array&gt; Octal for ArrayVec&lt;A&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;A::Item: Octal,&nbsp;</span>","synthetic":false,"types":[]},{"text":"impl&lt;A:&nbsp;Array&gt; Octal for TinyVec&lt;A&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;A::Item: Octal,&nbsp;</span>","synthetic":false,"types":[]}];
implementors["wayland_client"] = [{"text":"impl Octal for DndAction","synthetic":false,"types":[]},{"text":"impl Octal for Resize","synthetic":false,"types":[]},{"text":"impl Octal for Transient","synthetic":false,"types":[]},{"text":"impl Octal for Capability","synthetic":false,"types":[]},{"text":"impl Octal for Mode","synthetic":false,"types":[]}];
implementors["wayland_protocols"] = [{"text":"impl Octal for ContentHint","synthetic":false,"types":[]},{"text":"impl Octal for Anchor","synthetic":false,"types":[]},{"text":"impl Octal for Gravity","synthetic":false,"types":[]},{"text":"impl Octal for ConstraintAdjustment","synthetic":false,"types":[]},{"text":"impl Octal for Anchor","synthetic":false,"types":[]},{"text":"impl Octal for Flags","synthetic":false,"types":[]},{"text":"impl Octal for ConstraintAdjustment","synthetic":false,"types":[]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()