name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install libs
      run: sudo apt-get install libasound2
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --features fmod
    - name: Run tests
      run: cargo test --verbose --features fmod
