name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install nightly
      run: rustup install nightly
    - name: Install libs
      run: sudo apt-get install libasound2-dev
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --features fmod
    - name: Run tests
      run: cargo test --verbose
    - name: Document
      run: cargo +nightly doc --features "fmod document"
    - name: Deploy docs 🚀
      uses: JamesIves/github-pages-deploy-action@3.6.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: target/doc
        CLEAN: true